import React from 'react';

import Header from 'components/Header/Header.jsx';
import HeaderLinks from 'components/Header/HeaderLinks.jsx';
import withStyles from '@material-ui/core/styles/withStyles';
import Button from 'components/CustomButtons/Button.jsx';
import Auth from '@aws-amplify/auth';
import basicsStyle from 'assets/jss/material-kit-react/views/componentsSections/basicsStyle.jsx';
import { Icon } from 'semantic-ui-react';
import Amplify from '@aws-amplify/core';
import 'react-dropzone-uploader/dist/styles.css';
import PropTypes from 'prop-types';
import CookieBanner from 'react-cookie-banner';

class WelcomePage extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      user: null,
    };
    Amplify.configure({
      aws_appsync_authenticationType: 'API_KEY',
    });
    this.authenticate_user();
  }

  authenticate_user() {
    Auth.currentAuthenticatedUser()
      .then((user) => {
        console.log('uploadpage user', user.username);
        this.setState({ user: user });
        Amplify.configure({
          aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
        });
      })
      .catch((err) => {
        console.log(
          'currentAuthenticatedUser uploadpage er pushing to login page',
          err
        );
        this.setState({ user: null });
        Amplify.configure({
          aws_appsync_authenticationType: 'API_KEY',
        });
        //this.props.history.push("/login-page");
      });
  }

  render() {
    const { classes, ...rest } = this.props;

    return (
      <div style={{ minHeight: '100vh' }}>
        <Header
          fixed
          rightLinks={<HeaderLinks user={this.state.user} />}
          {...rest}
        />
        <div>
        <CookieBanner
            message="We use cookies to track login informations."
            onAccept={() => {}}
            cookie="user-has-accepted-cookies" />
          </div>
          <div
            className="section container"
            style={{
              backgroundImage: 'url(require("../assets/img/tail.jpg"))',
              backgroundPosition: 'center',
              backgroundSize: 'cover',
              backgroundRepeat: 'no-repeat',
            }}
          ></div>
          <div className={classes.container}>
            <div className="section container" style={{ paddingBottom: '5px' }}>
              <div className="row">
                <div className="col-12">
                  <div className="article-text">
                    <div
                      className={'text-center flex-row'}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        backgroundSize: '100vw auto',
                        minHeight: '400px',
                        backgroundImage:
                          'url("https://upload.wikimedia.org/wikipedia/commons/b/b8/Sperm_whale_pod.jpg")',
                        backgroundPosition: 'center',
                        backgroundSize: 'cover',
                        backgroundRepeat: 'no-repeat',
                      }}
                    >
                      <Button
                        color={'white'}
                        onClick={() => this.props.history.push('/upload')}
                      >
                        <Icon name="upload" />
                        Upload Whales
                      </Button>
                      <Button
                        color={'white'}
                        onClick={() =>
                          this.props.history.push('/browse-pictures')
                        }
                      >
                        <Icon name="search" />
                        Browse Whales
                      </Button>
                    </div>
                    <h1 style={{ paddingTop: '5px' }}>
                      <strong>FlukeTracker</strong>
                    </h1>
                    <h4 style={{ paddingTop: '5px', marginTop: '10px' }}>
                      <strong>What is the FlukeTracker website?</strong>
                    </h4>
                    <p style={{ paddingBottom: '5px' }}>
                      For Whale-Lovers: You can use this website to find sperm
                      whales and match your whale pictures with others.
                      <br></br> After uploading a whale image, potential matches
                      generated by the AI can be reviewed on the{' '}
                      <i>Match Whales</i> page.<br></br> Feel free to view our
                      entire whale catalogue on the <i> Browse Pictures </i>{' '}
                      page.
                    </p>
                    <video
                      id="vid"
                      src={require('../assets/mp4/whatcanyoudo.mp4')}
                      height="100%"
                      width="100%"
                      autoPlay
                      muted
                      loop
                    >
                      Ihr Browser kann dieses Video nicht wiedergeben.
                      <br />
                      Dieser Film zeigt eine Demonstration der Website. Sie
                      können ihn unter{' '}
                      <a href={require('../assets/mp4/whatcanyoudo.mp4')}>
                        Link-Addresse
                      </a>{' '}
                      abrufen.
                    </video>
                    <script>document.getElementById('vid').play();</script>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
        </div>
        <footer style={{backgroundColor: "#f3f3f3", margin: "20px 0px", padding:"20px", fontFamily: "Verdana, Arial, sans-serif"}}>
          <div className='container'>
        <div className='row'>
        <div style={{margin: "auto 100px auto 25px"}}>
        <p>All rights reserved by fluck-tracker. Copyright © 2020</p></div>
        <div style={{margin: "auto 100px auto 25px"}}>
        <a href="#" onClick={this.handleClick}>Privacy Policy</a></div>
        <div style={{margin: "auto 25px auto 25px"}}>
        <a href={"/term-of-use"} onClick={this.handleClick}>Term of Use</a></div>
        </div></div>
        </footer>
      </div>

    );
  }
}
WelcomePage.propTypes = {
  classes: PropTypes.element.isRequired,
  history: PropTypes.element.isRequired,
};

export default withStyles(basicsStyle)(WelcomePage);
