/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:74ecd986-0774-4828-856a-c17b93f38bbb",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_UgHnXIzga",
    "aws_user_pools_web_client_id": "53shrj6vsmmdd3bu1o8i8055mq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://bmzqnf6tm5chrckn3hqlgwue4m.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xyt72gbfmrcljm2zzstr4orvoi",
    "aws_content_delivery_bucket": "haleatch-20200418183437-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "https://d217scovboy5p.cloudfront.net",
    "aws_user_files_s3_bucket": "whalewatch315ac43cc81e4e31bd2ebcdca3e4bb09175546-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
