/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:2387faf7-47ae-4a47-b50a-a012330ec242",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_VLMtpxloM",
    "aws_user_pools_web_client_id": "696tanejsi9a6ts0v3csun2p8v",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://opky2tnssbhnbp3wxvvz2igcle.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "haleatch-20200418183437-hostingbucket-whaledev",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "https://d2jrjvkivy5vnq.cloudfront.net",
    "aws_user_files_s3_bucket": "whalewatch315ac43cc81e4e31bd2ebcdca3e4bb09213627-whaledev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
